### ISSUE TITLE
扫码后报错TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoUpdates')

### ISSUE THREAD

**Issue by kinger906** [wuba/Taro-Mortgage-Calculator#34]
ERROR  TypeError: undefined is not an object (evaluating '_expoModulesCore.NativeModulesProxy.ExpoUpdates')
 LOG  Running "taroDemo" with {"rootTag":11}
 ERROR  Invariant Violation: "taroDemo" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.

**Comment by zhiqingchen** [comment]
哪个版本的app进行扫码？
