### ISSUE TITLE
本地开发环境下如何在 Taro 壳项目中加载？

### ISSUE THREAD

**Issue by jecyu** [wuba/Taro-Mortgage-Calculator#50]

**Comment by zhiqingchen** [comment]
1. 启动该项目

```
yarn dev:rn
```

2. 下载或自行编译 shell 的dbug包

https://github.com/NervJS/taro-native-shell/releases

3. 用 usb 或 统一WiFi （原理同RN）

**Comment by jecyu** [comment]
> 1. 启动该项目
> 
> ```
> yarn dev:rn
> ```
> 
> 2. 下载或自行编译 shell 的dbug包
> 
> https://github.com/NervJS/taro-native-shell/releases
> 
> 3. 用 usb 或 同一WiFi （原理同RN）

好的，感谢
