### ISSUE TITLE
引入 import { AtInput } from 'taro-ui'; 报错 Unable to resolve module expo-asset

### ISSUE THREAD

**Issue by Sloth9527** [wuba/Taro-Mortgage-Calculator#57]
![企业微信截图_16754143346696](https://user-images.githubusercontent.com/20148778/216554929-0b939c41-1788-441e-bd70-4f803b42461b.png)

**Comment by Sloth9527** [comment]
![企业微信截图_16754147475320](https://user-images.githubusercontent.com/20148778/216556660-f8a2fdcd-8a47-4890-a2ef-2a8a07445d3f.png)

**Comment by zhiqingchen** [comment]
https://github.com/NervJS/taro-ui/issues/1424

**Comment by Sloth9527** [comment]
[taro-ui-demo-rn/package.json](https://github.com/NervJS/taro-ui/blob/bd62d2899df9e85de7d937f3812b3b68fe9d3b77/packages/taro-ui-demo-rn/package.json#L85) 

```
"expo-asset": "8.5.0",
```
